services:
  db:
    image: postgres:16-alpine
    container_name: marketplace_blog_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  test_db:
    image: postgres:16-alpine
    container_name: marketplace_blog_test_db
    env_file:
      - .env
    environment:
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: blog_password
      POSTGRES_DB: blog_test_db
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U blog_user -d blog_test_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: marketplace_blog_rabbitmq
    env_file:
      - .env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  minio:
    image: minio/minio:latest
    container_name: marketplace_blog_minio
    command: server /data --console-address ":9001"
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "${MINIO_PORT:-9000}:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  mailhog:
    image: mailhog/mailhog
    container_name: marketplace_blog_mailhog
    platform: linux/amd64
    ports:
      - "1025:1025"
      - "8025:8025"

  app:
    build: .
    container_name: marketplace_blog_app
    env_file:
      - .env
    ports:
      - "${WEB_PORT:-8000}:8000"
    volumes:
      - ./src:/app/src
      - ./alembic.ini:/app/alembic.ini
      - ./migrations:/app/migrations
    command: sh -c "alembic upgrade head && uvicorn src.marketplace_blog.main:app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_started
      minio:
        condition: service_started

  celery_worker:
    build: .
    container_name: marketplace_blog_celery
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    command: celery -A src.marketplace_blog.tasks worker --loglevel=info
    depends_on:
      rabbitmq:
        condition: service_started
      db:
        condition: service_healthy

volumes:
  postgres_data:
  minio_data:
  rabbitmq_data:
  test_postgres_data:
